// <auto-generated />
using System;
using DataAuth.Sample.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAuth.Sample.WebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230706075920_AddOrdersTable")]
    partial class AddOrdersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAuth.Sample.WebApi.Entities.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentDepartmentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentDepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "KDO",
                            Name = "Phòng Kinh doanh"
                        },
                        new
                        {
                            Id = 2,
                            Code = "KDO_CHA",
                            Name = "Bộ phận Cửa hàng",
                            ParentDepartmentId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "KDO_NVU",
                            Name = "Bộ phận Nghiệp vụ",
                            ParentDepartmentId = 2
                        },
                        new
                        {
                            Id = 4,
                            Code = "KDO_NVU_VTU",
                            Name = "Bộ phận Vật tư",
                            ParentDepartmentId = 3
                        },
                        new
                        {
                            Id = 5,
                            Code = "KDO_NVU_CTU",
                            Name = "Bộ phận Chứng từ hóa đơn",
                            ParentDepartmentId = 3
                        },
                        new
                        {
                            Id = 6,
                            Code = "KDO_CHA_NVB",
                            Name = "Nhân viên bán hàng",
                            ParentDepartmentId = 2
                        });
                });

            modelBuilder.Entity("DataAuth.Sample.WebApi.Entities.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CustomerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("DataAuth.Sample.WebApi.Entities.Province", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RegionId");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HCM",
                            Name = "Hồ Chí Minh",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 2,
                            Code = "TNI",
                            Name = "Tây Ninh",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 3,
                            Code = "BDU",
                            Name = "Bình Dương",
                            RegionId = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "DNI",
                            Name = "Đồng Nai",
                            RegionId = 3
                        });
                });

            modelBuilder.Entity("DataAuth.Sample.WebApi.Entities.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Regions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "Miền Bắc",
                            Name = "MB"
                        },
                        new
                        {
                            Id = 2,
                            Code = "Miền Trung",
                            Name = "MT"
                        },
                        new
                        {
                            Id = 3,
                            Code = "Miền Nam",
                            Name = "MN"
                        });
                });

            modelBuilder.Entity("DataAuth.Sample.WebApi.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceId");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "HCM_001",
                            Name = "Cửa hàng Trần Hưng Đạo",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "HCM_002",
                            Name = "Cửa hàng Nguyễn Văn Cừ",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 3,
                            Code = "HCM_003",
                            Name = "Cửa hàng Nguyễn Oanh",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 4,
                            Code = "HCM_004",
                            Name = "Cửa hàng Phan Đăng Lưu",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 5,
                            Code = "HCM_005",
                            Name = "Cửa hàng Võ Văn Việt",
                            ProvinceId = 1
                        },
                        new
                        {
                            Id = 6,
                            Code = "DNI_001",
                            Name = "Cửa hàng Biên Hòa 1",
                            ProvinceId = 4
                        },
                        new
                        {
                            Id = 7,
                            Code = "BDU_001",
                            Name = "Cửa hàng Dĩ An",
                            ProvinceId = 3
                        });
                });

            modelBuilder.Entity("DataAuth.Sample.WebApi.Entities.Department", b =>
                {
                    b.HasOne("DataAuth.Sample.WebApi.Entities.Department", "ParentDepartment")
                        .WithMany()
                        .HasForeignKey("ParentDepartmentId");

                    b.Navigation("ParentDepartment");
                });

            modelBuilder.Entity("DataAuth.Sample.WebApi.Entities.Order", b =>
                {
                    b.HasOne("DataAuth.Sample.WebApi.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("DataAuth.Sample.WebApi.Entities.Province", b =>
                {
                    b.HasOne("DataAuth.Sample.WebApi.Entities.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");
                });

            modelBuilder.Entity("DataAuth.Sample.WebApi.Entities.Store", b =>
                {
                    b.HasOne("DataAuth.Sample.WebApi.Entities.Province", "Province")
                        .WithMany()
                        .HasForeignKey("ProvinceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Province");
                });
#pragma warning restore 612, 618
        }
    }
}
