name: Build and Test
on:
  push:
    branches:
      - master
jobs:
  tests:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.0.20"

      - name: Restore dependencies
        run: dotnet restore src

      - name: Build project
        run: dotnet build src --configuration Release --no-restore

      - name: Run unit tests
        run: dotnet test src
