name: Publish package
on: workflow_dispatch
jobs:
  pack:
    name: Packaging and publish
    runs-on: windows-latest
    defaults:
      run:
        working-directory: src/DataAuth
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Restore dependencies
        run: dotnet restore

      - name: Pack project
        run: dotnet pack --configuration Release

      - name: Get version
        id: package_version
        uses: KageKirin/get-csproj-version@v1.0.0
        with:
          file: DataAuth/DataAuth.csproj

      - name: Publish to Github
        run: |
          dotnet nuget add source --username dragonlong206 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/NAMESPACE/index.json"
          dotnet nuget push "bin/Release/DataAuth.${{ steps.package_version.version }}.nupkg" --source "github"
